### ISSUE TITLE
Metadata: `filamentUsage` & `materialUsage`

### ISSUE THREAD

**Issue by benzend** [Cloud-CNC/cura-wasm#14]
I'm curious if we're able to get the estimated weight when you slice STL files as I believe Cura has this. Also what do the meta variables mean exactly? `filamentUsage` and `materialUsage` aren't really stated well and I have no idea what they mean.

Also what type of units is `printTime` in?

Update [Solved]: 

```
filamentUsage: length in mm3
materialUsage: length in mm3
printTime: seconds
```

**Comment by Wakeful-Cloud** [comment]
I think I forgot to add comments about the units in V1, I'll be sure to add comments in V2 though - sorry! For future reference: [`demo/index.js`](https://github.com/Cloud-CNC/cura-wasm/blob/09c61a5c0519991eafa21b39c44e68c4715d9f09/demo/index.js#L80) and [`docker/CuraEngine.patch`](https://github.com/Cloud-CNC/cura-wasm/blob/09c61a5c0519991eafa21b39c44e68c4715d9f09/docker/CuraEngine.patch#L62)
