### ISSUE TITLE
Types definition point to inexistent folder

### ISSUE THREAD

**Issue by brunobasto** [Cloud-CNC/cura-wasm#9]
Hello! Me again :)

https://github.com/Cloud-CNC/cura-wasm/blob/master/package.json#L7

I couldn't find cura-wasm/dist/types inside my node_modules. VSCode gives me compilation errors.

**Comment by Wakeful-Cloud** [comment]
Hmm that's odd. Are you still running V1.3.3?

**Comment by brunobasto** [comment]
Yes. Just checked. It's still 1.3.3. For me, there's no `types` folder inside `dist`:

![Screen Shot 2020-11-30 at 8 32 53 PM](https://user-images.githubusercontent.com/156388/100678127-3afaa280-334b-11eb-93f7-f1e234b11dea.png)

I noticed this yesterday because I'm migrating my little project to typescript (while it's still small 🤣 )

**Comment by Wakeful-Cloud** [comment]
The types live inside of the `cjs` and `es` directories. Currently, the `package.json` points to the nonexistent `types` directory but this will be fixed very soon. In the meantime, you can change the `"types"` field in Cura WASM's package.json to `"types": "dist/es/index.d.ts",`.

**Comment by Wakeful-Cloud** [comment]
Please update to version 1.4.2 - switched to named exports, separated definitions to separate package ([`cura-wasm-definitions`](https://github.com/cloud-cnc/cura-wasm-definitions)), and fixed the package.json issues. Apologies for the confusion and thanks for filing.

**Comment by brunobasto** [comment]
Awesome. Thank you
